=== alexfdzs/SEW/xml/rutas.xsd
<?xml version="1.0" encoding="Windows-1252"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.uniovi.es"
  xmlns="http://www.uniovi.es"
  elementFormDefault="qualified">

  <xs:element name="rutas">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="3" maxOccurs="unbounded" ref="ruta" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ruta">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tipo" minOccurs="1" maxOccurs="1" />
        <xs:element ref="medio_transporte" minOccurs="1" maxOccurs="1" />
        <xs:element ref="duracion" minOccurs="1" maxOccurs="1" />
        <xs:element ref="agencia" minOccurs="1" maxOccurs="1" />
        <xs:element ref="descripcion" minOccurs="1" maxOccurs="1" />
        <xs:element ref="personas_adecuadas" minOccurs="1" maxOccurs="1" />
        <xs:element ref="inicio_ruta" minOccurs="1" maxOccurs="1" />
        <xs:element ref="referencias" minOccurs="1" maxOccurs="1" />
        <xs:element ref="recomendacion" minOccurs="1" maxOccurs="1" />
        <xs:element ref="hitos" minOccurs="1" maxOccurs="1" />
      </xs:sequence>
      <xs:attribute name="nombre" type="xs:string" use="required" />
      <xs:attribute name="fecha_inicio" type="xs:date" use="optional" />
      <xs:attribute name="fecha_final" type="xs:date" use="optional" />
    </xs:complexType>
  </xs:element>
  <xs:element name="tipo" type="xs:string" />
  <xs:element name="medio_transporte" type="xs:string" />
  <xs:element name="duracion" type="xs:duration" />
  <xs:element name="agencia" type="xs:string" />
  <xs:element name="descripcion" type="xs:string" />
  <xs:element name="personas_adecuadas" type="xs:string" />
  <xs:element name="inicio_ruta">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="coordenadas" minOccurs="1" maxOccurs="1" />
      </xs:sequence>
      <xs:attribute name="lugar" type="xs:string" use="required" />
      <xs:attribute name="direccion" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="referencias">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="referencia" type="xs:string" />
  <xs:element name="recomendacion" type="xs:integer" />
  <xs:element name="hitos">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="3" maxOccurs="unbounded" ref="hito" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="hito">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="descripcion" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="coordenadas" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="distancia" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="galeria_foto" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="galeria_video" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="nombre" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="galeria_foto">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="foto" minOccurs="1" maxOccurs="5"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="galeria_video">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="video" minOccurs="1" maxOccurs="3" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="foto" type="xs:anyURI" />
  <xs:element name="video" type="xs:string" />
  <xs:element name="coordenadas">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:float">
          <xs:attribute name="latitud" type="xs:float" use="required" />
          <xs:attribute name="longitud" type="xs:float" use="required" />
          <xs:attribute name="alt_measure" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="distancia">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:float">
          <xs:attribute name="dist_measure" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== alexfdzs/SEW/xml/rutasEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<rutas
    xmlns="http://www.uniovi.es"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.uniovi.es rutas.xsd">

    <ruta nombre="Tanji River Paddle">
        <tipo>Paisajística</tipo>
        <medio_transporte>Canoa</medio_transporte>
        <duracion>PT4H</duracion>
        <agencia>Trekking Hiking</agencia>
        <descripcion> Explora esta ruta de ida y vuelta de 7,2-km cerca de Tujering, West Coast. Un
            corto viaje en canoa por un pequeño río que desemboca en el mar en Tanji.</descripcion>
        <personas_adecuadas> Personas en buena forma física</personas_adecuadas>
        <inicio_ruta lugar="Carretera Coastal Road" direccion="9663+27J, Coastal Rd, Tanji, Gambia">
            <coordenadas latitud="13.360393649810536" longitud="-16.796886725805148" alt_measure="m">
                8</coordenadas>
        </inicio_ruta>
        <referencias>
            <referencia>
                https://es.wikiloc.com/rutas-senderismo/tanji-river-paddle-facil-tujering-west-coast-gambia-145371314
                </referencia>
            <referencia> https://www.alltrails.com/es/ruta/the-gambia/west-coast/tanji-river-paddle </referencia>
            <referencia>
                https://www.tripadvisor.es/Attraction_Review-g3675810-d17473776-Reviews-Gambia_Kayaking-Tanji_West_Coast_Division.html
                </referencia>
        </referencias>
        <recomendacion>7</recomendacion>
        <hitos>
            <hito nombre="Tanji River Entrance">
                <descripcion>Entrada al rio Tanji</descripcion>
                <coordenadas latitud="13.360171851335481" longitud="-16.796894133622303"
                    alt_measure="m">8</coordenadas>
                <distancia dist_measure="km">0</distancia>
                <galeria_foto>
                    <foto>
                        xml/multimedia/Tanji_River_Paddle/Tanji_River_Entrance/tanji_river_entrance.png</foto>
                </galeria_foto>
            </hito>
            <hito nombre="Tanji Statue">
                <descripcion>Estatua que representa las aldeas antiguas que habitaban alrededor del
                    río Tanji</descripcion>
                <coordenadas latitud="13.362881713084317" longitud="-16.78921401225453"
                    alt_measure="m">13</coordenadas>
                <distancia dist_measure="km">16</distancia>
                <galeria_foto>
                    <foto>xml/multimedia/Tanji_River_Paddle/Tanji_Statue/tanji_statue.png</foto>
                </galeria_foto>
            </hito>
            <hito nombre="Fallen Tree">
                <descripcion>Árbol antiguo caído a la vera del río</descripcion>
                <coordenadas latitud="13.358817621816417" longitud="-16.784624582863934"
                    alt_measure="m">20</coordenadas>
                <distancia dist_measure="km">5.23</distancia>
                <galeria_foto>
                    <foto>xml/multimedia/Tanji_River_Paddle/Tanji_Fallen_Tree/tanji_fallen_tree.png</foto>
                </galeria_foto>
            </hito>
            <hito nombre="Final">
                <descripcion>Entrada al rio Tanji. lugar de final</descripcion>
                <coordenadas latitud="13.360171851335481" longitud="-16.796894133622303"
                    alt_measure="m">8</coordenadas>
                <distancia dist_measure="km">7.21</distancia>
                <galeria_foto>
                    <foto>
                        xml/multimedia/Tanji_River_Paddle/Tanji_River_Entrance/tanji_river_entrance.png</foto>
                </galeria_foto>
            </hito>
        </hitos>
    </ruta>

    <ruta nombre="Kartong">
        <tipo>Paisajística</tipo>
        <medio_transporte>A pie</medio_transporte>
        <duracion>PT2H30M</duracion>
        <agencia> Carsali</agencia>
        <descripcion> Paseo por el pueblo de Kartong, pueblo costero en el suroeste de Gambia en la
            frontera con Senegal.</descripcion>
        <personas_adecuadas> Cualquiera</personas_adecuadas>
        <inicio_ruta lugar="Restaurante Doudou's" direccion="Kartong crossing point, Gambia">
            <coordenadas latitud="13.073584406863601" longitud="-16.743567420853864" alt_measure="m">
                30</coordenadas>
        </inicio_ruta>
        <referencias>
            <referencia>https://es.wikiloc.com/rutas-a-pie/kartong-gambia-126348141</referencia>
            <referencia> https://en.wikipedia.org/wiki/Kartung </referencia>
            <referencia>
                https://www.conbotasymochila.com/viaje-a-gambia-ii-kartong-y-frontera-con-senegal/ </referencia>
        </referencias>
        <recomendacion>8</recomendacion>
        <hitos>
            <hito nombre="Restaurante Doudou's">
                <descripcion>Restaurante situado en Kartong. Lugar de salida y donde poder comprar
                    comida para la actividad.</descripcion>
                <coordenadas latitud="13.073584406863601" longitud="-16.743567420853864"
                    alt_measure="m">30</coordenadas>
                <distancia dist_measure="km">0</distancia>
                <galeria_foto>
                    <foto>xml/multimedia/Kartong/Restaurante_Doudous/restaurante_doudous.png</foto>
                </galeria_foto>
            </hito>
            <hito nombre="Arbol pie de nius">
                <descripcion>Arbol pie de nius.</descripcion>
                <coordenadas latitud="13.073803872479798" longitud="-16.747011377111054"
                    alt_measure="m">38</coordenadas>
                <distancia dist_measure="km">0.7</distancia>
                <galeria_foto>
                    <foto>xml/multimedia/Kartong/nius_tree/nius_tree.png</foto>
                </galeria_foto>
            </hito>
            <hito nombre="Pescadores, pelicanos y buitres">
                <descripcion>Zona donde pescadores descargan el barco. Además, hay pelícanos y
                    buitres que intentan robar la pesca.</descripcion>
                <coordenadas latitud="13.072643710275129" longitud="-16.752897632131326"
                    alt_measure="m">0</coordenadas>
                <distancia dist_measure="km">1.7</distancia>
                <galeria_foto>
                    <foto>xml/multimedia/Kartong/Pescadors/pescadores.png</foto>
                </galeria_foto>
            </hito>
            <hito nombre="Final">
                <descripcion>Restaurante situado en Kartong. Lugar de final.</descripcion>
                <coordenadas latitud="13.073584406863601" longitud="-16.743567420853864"
                    alt_measure="m">30</coordenadas>
                <distancia dist_measure="km">5.23</distancia>
                <galeria_foto>
                    <foto>xml/multimedia/Kartong/Restaurante_Doudous/restaurante_doudous.png</foto>
                </galeria_foto>
            </hito>
        </hitos>
    </ruta>


    <ruta nombre="JJB a Kumbanyerr East">
        <tipo>Senderismo y paisajistica</tipo>
        <medio_transporte>A pie</medio_transporte>
        <duracion>PT5H</duracion>
        <agencia> Gernot Henn</agencia>
        <descripcion> Desde Janjanbureh en la isla Mc Carthy en dirección este hasta Kumbanyerr
            (final de la isla). Regreso por el mismo camino. Total 13 km.</descripcion>
        <personas_adecuadas> Personas en buena forma física</personas_adecuadas>
        <inicio_ruta lugar="Janjanbureh" direccion="G6RP+W43, Janjanbureh, Gambia">
            <coordenadas latitud="13.54265755161999" longitud="-14.764665918285672" alt_measure="m">
                7</coordenadas>
        </inicio_ruta>
        <referencias>
            <referencia>
                https://www.outdooractive.com/en/route/hiking-route/gambia/jjb-to-kumbanyerr-east-on-island/118835332/#dmdtab=oax-tab3
                </referencia>
            <referencia> https://en.wikipedia.org/wiki/Janjanbureh </referencia>
            <referencia>
                https://gernothenn.wixsite.com/gambia/post/baobab-hiking-trail-progress-report-03</referencia>
        </referencias>
        <recomendacion>6</recomendacion>
        <hitos>
            <hito nombre="Janjanbureh Health Clinic">
                <descripcion>Clínica de salud situada en el centro de JanjanBureh. Lugar de inicio.</descripcion>
                <coordenadas latitud="13.54265755161999" longitud="-14.764665918285672"
                    alt_measure="m"> 7</coordenadas>
                <distancia dist_measure="km">0</distancia>
                <galeria_foto>
                    <foto>xml/multimedia/JBB/JBB_Clinic/jbb_clinic.jpg</foto>
                </galeria_foto>
            </hito>
            <hito nombre="Kunkilling Forest Park">
                <descripcion>Parque forestal, establecido el 1 de enero de 1954. Abarca un total de
                    143 hectáreas.</descripcion>
                <coordenadas latitud="13.543035921408894" longitud="-14.764012204261391"
                    alt_measure="m">15</coordenadas>
                <distancia dist_measure="km">5</distancia>
                <galeria_foto>
                    <foto>xml/multimedia/JBB/Kunkilling_Park/kunkilling_park.jpg</foto>
                </galeria_foto>
            </hito>
            <hito nombre="Freedom Tree Monument">
                <descripcion>El Árbol de la Libertad es un símbolo de crecimiento y continuidad.</descripcion>
                <coordenadas latitud="13.528505406482957" longitud="-14.723116764565285"
                    alt_measure="m">20</coordenadas>
                <distancia dist_measure="km">7.4</distancia>
                <galeria_foto>
                    <foto>xml/multimedia/JBB/Fredom_Tree/fredom_tree.png</foto>
                </galeria_foto>
            </hito>
